FROM node:20-alpine AS builder

WORKDIR /app

COPY . .

RUN npm ci
RUN npx nx build api

# ---- runtime ----
FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/dist/api ./

RUN npm install --omit=dev

CMD ["node", "main.js"]