# ---- BUILD STAGE ----
FROM node:22-alpine AS builder

WORKDIR /app
COPY package*.json ./

RUN npm ci
COPY . .
RUN npx nx build api --configuration=production

# ---- PRODUCTION STAGE ----
FROM node:22-alpine

WORKDIR /app
ENV NODE_ENV=production

COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=builder /app/dist/api ./

EXPOSE 3000
CMD ["node", "main.js"]