FROM node:20-alpine AS builder

WORKDIR /app

COPY . .

RUN npm ci
RUN npx nx build web --configuration=production

# ---- nginx ----
FROM nginx:alpine

COPY --from=builder /app/dist/web /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]