services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - '4200:80'
    depends_on:
      - api

volumes:
  postgres_data: